package edu.sakp.mapper;

import edu.sakp.pojo.Statistics;
import edu.sakp.pojo.StatisticsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    long countByExample(StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    int deleteByExample(StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    int insert(Statistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    int insertSelective(Statistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    List<Statistics> selectByExample(StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    Statistics selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") Statistics record, @Param("example") StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    int updateByExample(@Param("record") Statistics record, @Param("example") StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    int updateByPrimaryKeySelective(Statistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    int updateByPrimaryKey(Statistics record);
}