package edu.sakp.pojo;

import java.io.Serializable;
import java.util.Date;

public class Batch extends BaseBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch.id
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch.name
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch.create_time
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch.start_time
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch.end_time
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch.status
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch.id
     *
     * @return the value of batch.id
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch.id
     *
     * @param id the value for batch.id
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch.name
     *
     * @return the value of batch.name
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch.name
     *
     * @param name the value for batch.name
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch.create_time
     *
     * @return the value of batch.create_time
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch.create_time
     *
     * @param createTime the value for batch.create_time
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch.start_time
     *
     * @return the value of batch.start_time
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch.start_time
     *
     * @param startTime the value for batch.start_time
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch.end_time
     *
     * @return the value of batch.end_time
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch.end_time
     *
     * @param endTime the value for batch.end_time
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch.status
     *
     * @return the value of batch.status
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch.status
     *
     * @param status the value for batch.status
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

}