package edu.sakp.pojo;

import java.util.Date;

public class Statistics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics.id
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics.user_id
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics.name
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics.stu_no
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    private String stuNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics.batch_id
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    private Integer batchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics.content
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics.create_time
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics.id
     *
     * @return the value of statistics.id
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics.id
     *
     * @param id the value for statistics.id
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics.user_id
     *
     * @return the value of statistics.user_id
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics.user_id
     *
     * @param userId the value for statistics.user_id
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics.name
     *
     * @return the value of statistics.name
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics.name
     *
     * @param name the value for statistics.name
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics.stu_no
     *
     * @return the value of statistics.stu_no
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public String getStuNo() {
        return stuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics.stu_no
     *
     * @param stuNo the value for statistics.stu_no
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public void setStuNo(String stuNo) {
        this.stuNo = stuNo == null ? null : stuNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics.batch_id
     *
     * @return the value of statistics.batch_id
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public Integer getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics.batch_id
     *
     * @param batchId the value for statistics.batch_id
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics.content
     *
     * @return the value of statistics.content
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics.content
     *
     * @param content the value for statistics.content
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics.create_time
     *
     * @return the value of statistics.create_time
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics.create_time
     *
     * @param createTime the value for statistics.create_time
     *
     * @mbg.generated Wed May 06 19:43:32 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}